---
language: node_js
node_js:
  - node
  - lts/*
branches:
  only:
  - development
  - master
notifications:
  webhooks:
    - $SLACK_WEBHOOK
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  # - npm ci
  # - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
        - sudo sysctl -p
        - npm install --save-dev expo-cli
        - npx expo login --non-interactive -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive --release-channel development
      after_script:
        - sudo bash slack_script.sh $SLACK_WEBHOOK dev
