---
language: node_js
node_js:
  - node
  - lts/*
notifications:
  slack: cnhtech1920:UPmFebRU4eqD0OpXnCm5dlwg
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  # - npm ci
  # - npx jest --ci
jobs:
  include:
    - stage: publish-development
      if: branch = development
      node_js: lts/*
      script:
        - npm ci
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
        - sudo sysctl -p
        - npm install --save-dev expo-cli
        - npx expo login --non-interactive -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive --release-channel development
      after_success:
        - sudo bash slack_script.sh $SLACK_WEBHOOK dev
    - stage: publish-master
      if: branch = master_ci_pipeline AND sender != "cnhtech-software"
      script:
        - npm ci
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
        - sudo sysctl -p
        - node buildscript.js $GH_TOKEN
        - npm install --save-dev expo-cli
        - npx expo login --non-interactive -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive --release-channel citest
      after_success:
        - sudo bash slack_script.sh $SLACK_WEBHOOK master
